import type { Metadata } from "next";
import "./globals.css";
import localFont from 'next/font/local'
import { LenisProvider } from "@/components/ScrollSmooth";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";
import IntroLoader from "@/components/sections/IntroLoader";

const garamondBook = localFont({
  src: '../../public/fonts/itc-garamond-std-book-narrow.otf',
  variable: '--font-garamond',
  display: 'swap',
})

const rocBold = localFont({
  src: '../../public/fonts/roc-grotesk-compressed-bold.otf',
  variable: '--font-roc-bold',
  display: 'swap',
})

const rocCondensed = localFont({
  src: '../../public/fonts/roc-grotesk-condensed.otf',
  variable: '--font-roc-condensed',
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      className={`${garamondBook.variable} ${rocBold.variable} ${rocCondensed.variable} antialiased`}
      >
        <LenisProvider>
        <Navbar />
        {children}
        <Footer />
        </LenisProvider>
      </body>
    </html>
  );
}
